#!/usr/bin/env node
/**
 * Stage 7 list pipeline (PLAN Workstream C: "list-update pipeline for bots.yml, referrer spam and
 * datacentre ASNs, with a diff review step").
 *
 *   node tools/lists.mjs generate   rebuild the TypeScript modules from infra/lists/* (offline, deterministic)
 *   node tools/lists.mjs check      fail if the generated modules are out of date (CI)
 *   node tools/lists.mjs update     download the newest upstream lists, PRINT THE DIFF, write them,
 *                                   regenerate. Review the diff + run the regression corpus before committing.
 *
 * Sources (licences in infra/lists/SOURCES.md):
 *   matomo-bots.yml            matomo-org/device-detector regexes/bots.yml   LGPL-3.0-or-later (data, kept verbatim)
 *   matomo-referrer-spam.txt   matomo-org/referrer-spam-list spammers.txt    Public domain
 *   bad-asn-list.csv           brianhama/bad-asn-list                        MIT
 *   asn-overrides.json         ours: never-drop ASNs (residential ISPs, privacy relays) + additions
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const LISTS = here('../lists/');
const OUT = {
  bots: here('../../apps/consumer/src/precision/lists/bots.generated.ts'),
  spam: here('../../apps/consumer/src/precision/lists/referrer-spam.generated.ts'),
  asns: here('../../packages/contract/src/lists/datacentre-asns.generated.ts'),
};
const UPSTREAM = {
  'matomo-bots.yml': { repo: 'matomo-org/device-detector', path: 'regexes/bots.yml' },
  'matomo-referrer-spam.txt': { repo: 'matomo-org/referrer-spam-list', path: 'spammers.txt' },
  'bad-asn-list.csv': { repo: 'brianhama/bad-asn-list', path: 'bad-asn-list.csv' },
};

const read = (name) => readFileSync(LISTS + name, 'utf8');
const sha = (text) => createHash('sha256').update(text).digest('hex').slice(0, 16);
const HEADER = (source, text) =>
  `// GENERATED by infra/tools/lists.mjs from infra/lists/${source} (sha256 ${sha(text)}). Do not edit.\n` +
  `// Regenerate: pnpm lists:generate. Licence: infra/lists/SOURCES.md\n`;

// ---------------------------------------------------------------- parsers (also used by `update` for the diff)

/** bots.yml -> [{ regex, name, category }]. Every regex must compile as a JS RegExp. */
export function parseBots(text) {
  const list = YAML.parse(text);
  if (!Array.isArray(list)) throw new Error('bots.yml: not a list');
  return list.map((b, i) => {
    if (typeof b?.regex !== 'string' || typeof b?.name !== 'string') throw new Error(`bots.yml entry ${i}: no regex/name`);
    // Exactly how device-detector applies it (Parser/AbstractParser::matchUserAgent).
    new RegExp(`(?:^|[^A-Z0-9_\\-])(?:${b.regex})`, 'i');
    return { regex: b.regex, name: b.name, category: typeof b.category === 'string' ? b.category : '' };
  });
}

export function parseSpam(text) {
  const out = new Set();
  for (const raw of text.split(/\r?\n/)) {
    const d = raw.trim().toLowerCase().replace(/\.$/, '');
    if (!d || d.startsWith('#')) continue;
    if (!/^[a-z0-9.-]+\.[a-z0-9-]+$/.test(d)) throw new Error(`referrer spam: not a domain: ${raw}`);
    out.add(d);
  }
  return [...out].sort();
}

export function parseAsnCsv(text) {
  const out = new Map();
  for (const line of text.split(/\r?\n/).slice(1)) {
    const m = line.match(/^(\d+),(.*)$/);
    if (m) out.set(Number(m[1]), m[2].replace(/^"|"$/g, ''));
  }
  return out;
}

function asnSet() {
  const upstream = parseAsnCsv(read('bad-asn-list.csv'));
  const ov = JSON.parse(read('asn-overrides.json'));
  const never = new Map(ov.never.map((e) => [e.asn, e]));
  const set = new Map();
  for (const [asn, name] of upstream) if (!never.has(asn)) set.set(asn, name);
  for (const e of ov.add) if (!never.has(e.asn)) set.set(e.asn, e.name);
  return { set, upstream, never };
}

// ---------------------------------------------------------------- generate

function generated() {
  const botsText = read('matomo-bots.yml');
  const bots = parseBots(botsText);
  const spamText = read('matomo-referrer-spam.txt');
  const spam = parseSpam(spamText);
  const asnText = read('bad-asn-list.csv') + read('asn-overrides.json');
  const { set } = asnSet();
  const asns = [...set.keys()].sort((a, b) => a - b);

  return {
    bots:
      HEADER('matomo-bots.yml', botsText) +
      `// ${bots.length} entries, in upstream order (first match wins, as in device-detector).\n` +
      `export interface BotEntry { regex: string; name: string; category: string }\n` +
      `export const BOTS: readonly BotEntry[] = ${JSON.stringify(bots, null, 0).replaceAll('},{', '},\n  {').replace('[{', '[\n  {').replace(/}]$/, '},\n]')};\n`,
    spam:
      HEADER('matomo-referrer-spam.txt', spamText) +
      `// ${spam.length} domains. A referrer matches when its host IS one of them or a subdomain of one.\n` +
      `export const REFERRER_SPAM: readonly string[] = [\n${spam.map((d) => `  '${d}',`).join('\n')}\n];\n`,
    asns:
      HEADER('bad-asn-list.csv + asn-overrides.json', asnText) +
      `// ${asns.length} datacentre / hosting ASNs, minus the never-drop overrides (residential ISPs, privacy relays).\n` +
      `export const DATACENTRE_ASN_LIST: readonly number[] = [\n${chunk(asns, 12).map((r) => `  ${r.join(', ')},`).join('\n')}\n];\n`,
  };
}

const chunk = (a, n) => Array.from({ length: Math.ceil(a.length / n) }, (_, i) => a.slice(i * n, i * n + n));

function generate() {
  const g = generated();
  for (const k of Object.keys(OUT)) writeFileSync(OUT[k], g[k]);
  console.log('generated:\n  ' + Object.values(OUT).map((p) => p.replace(here('../../'), '')).join('\n  '));
}

function check() {
  const g = generated();
  const stale = Object.keys(OUT).filter((k) => {
    try {
      return readFileSync(OUT[k], 'utf8') !== g[k];
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`lists: generated modules out of date: ${stale.join(', ')}. Run: pnpm lists:generate`);
    process.exit(1);
  }
  console.log('lists: generated modules match infra/lists ✔');
}

// ---------------------------------------------------------------- update (with the diff review step)

function headCommit(repo) {
  const out = execFileSync('git', ['ls-remote', `https://github.com/${repo}`, 'HEAD'], { encoding: 'utf8' });
  const commit = out.split(/\s/)[0];
  if (!/^[0-9a-f]{40}$/.test(commit ?? '')) throw new Error(`could not resolve HEAD of ${repo}`);
  return commit;
}

function diff(label, before, after) {
  const b = new Set(before);
  const a = new Set(after);
  const added = [...a].filter((x) => !b.has(x));
  const removed = [...b].filter((x) => !a.has(x));
  console.log(`\n${label}: ${before.length} -> ${after.length}  (+${added.length} / -${removed.length})`);
  for (const x of added.slice(0, 50)) console.log(`  + ${x}`);
  if (added.length > 50) console.log(`  … ${added.length - 50} more added`);
  for (const x of removed.slice(0, 50)) console.log(`  - ${x}`);
  if (removed.length > 50) console.log(`  … ${removed.length - 50} more removed`);
}

async function update() {
  const sources = JSON.parse(read('sources.json'));
  for (const [file, { repo, path }] of Object.entries(UPSTREAM)) {
    const commit = headCommit(repo);
    const url = `https://raw.githubusercontent.com/${repo}/${commit}/${path}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
    const text = await res.text();
    const old = read(file);
    if (file.endsWith('.yml')) diff(file, parseBots(old).map((b) => `${b.name}  /${b.regex}/`), parseBots(text).map((b) => `${b.name}  /${b.regex}/`));
    else if (file.endsWith('.txt')) diff(file, parseSpam(old), parseSpam(text));
    else diff(file, [...parseAsnCsv(old)].map(([n, s]) => `${n} ${s}`), [...parseAsnCsv(text)].map(([n, s]) => `${n} ${s}`));
    writeFileSync(LISTS + file, text);
    sources[file] = { ...sources[file], repo, path, commit, sha256: createHash('sha256').update(text).digest('hex'), fetched: new Date().toISOString().slice(0, 10) };
  }
  writeFileSync(LISTS + 'sources.json', JSON.stringify(sources, null, 2) + '\n');
  generate();
  console.log('\nREVIEW the diff above (especially new ASNs: is any of them a home/mobile ISP? add it to');
  console.log('asn-overrides.json "never"), then run: pnpm --filter @tailwatch/consumer test  (regression corpus)');
}

const cmd = process.argv[2];
if (cmd === 'generate') generate();
else if (cmd === 'check') check();
else if (cmd === 'update') await update();
else if (cmd !== undefined) {
  console.error('usage: node tools/lists.mjs generate | check | update');
  process.exit(2);
}
